
# Azure Infrastructure using Azure Verified Modules (AVM)
# Generated by Azure DevOps Agent

terraform {
  required_version = ">= 1.0"
  
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  
  backend "azurerm" {
    storage_account_name = "stuksmcsnbxtfstate"
    container_name       = "tfstate"
    key                  = "dev/terraform.tfstate"
    resource_group_name  = "rg-uks-mc-snbx-rg"
    use_azuread_auth    = true
  }
}

provider "azurerm" {
  features {}
}

# Local values for consistent naming
locals {
  common_tags = {
    Environment = var.environment
    Project     = var.project_name
    ManagedBy   = "terraform"
    CreatedBy   = "azure-devops-agent"
  }
}

# AVM Modules will be generated here
# 3 modules planned
