# Terraform Outputs
# Generated by CloudAssist

output "resource_group_name" {
  description = "Name of the created resource group"
  value       = azurerm_resource_group.main.name
}

output "resource_group_location" {
  description = "Location of the resource group"
  value       = azurerm_resource_group.main.location
}







output "deployment_timestamp" {
  description = "Timestamp of the deployment"
  value       = timestamp()
}
