# Terraform Variables
# Generated by CloudAssist

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
  
  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be one of: dev, staging, prod."
  }
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "UK South"
}

variable "resource_group_name" {
  description = "Name of the resource group"
  type        = string
  default     = "rg-${var.environment}-cloudassist"
}

variable "common_tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default = {
    Environment = var.environment
    Project     = "CloudAssist"
    ManagedBy   = "Terraform"
    CreatedBy   = "GitOps"
  }
}

# Application-specific variables






# Random suffix for unique resource names
resource "random_id" "suffix" {
  byte_length = 4
}
