# Generated by DevOps AI Agent
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "rg-devops-ai-test"
  location = "East US"

  tags = {
    Environment = "test"
    ManagedBy   = "devops-ai-agent"
  }
}