# Generated by DevOps AI Agent via GitOps Integration
# Environment: dev
# Generated: 2025-09-04T22:05:22.194706
# Original Request: Deploy Ubuntu VM with public IP
# GitOps Repository: azurecloud-poc

# Common tags for all resources
locals {
  common_tags = {
    Environment     = "dev"
    ManagedBy      = "devops-ai-agent"
    GitOpsRepo     = "azurecloud-poc"
    DeploymentDate = "2025-09-04"
    OriginalRequest = substr("Deploy Ubuntu VM with public IP", 0, 100)
  }
}

# Resource Group
module "resource_group" {
  source  = "Azure/avm-res-resources-resourcegroup/azurerm"
  version = "~> 0.1"
  name     = var.resource_group_name
  location = var.location
}
# Virtual Machine
module "virtual_machine" {
  source  = "Azure/avm-res-compute/virtualmachine/azurerm"
  version = "~> 0.1.0"
  name = var.name
  specifications = var.specifications
  resource_group_name = module.resource_group.name
  location            = var.location
  size = var.size
  admin_username = var.admin_username
  os_disk = var.os_disk
  os_type = var.os_type
  os_image = var.os_image
}