# Generated by DevOps AI Agent via GitOps Integration
# Environment: dev
# Generated: 2025-09-04T20:57:11.190214
# Original Request: create resource group called demo-gitops-rg in West US and deploy
# GitOps Repository: azurecloud-poc

# Common tags for all resources
locals {
  common_tags = {
    Environment     = "dev"
    ManagedBy      = "devops-ai-agent"
    GitOpsRepo     = "azurecloud-poc"
    DeploymentDate = "2025-09-04"
    OriginalRequest = substr("create resource group called demo-gitops-rg in West US and deploy", 0, 100)
  }
}

# Resource Group
module "resource_group" {
  source  = "Azure/terraform-azurerm-avm-res-resources-resourcegroup/azurerm"
  version = "~> 0.1.0"
  name = var.name
  location            = var.location
}