# DEV Environment Variables
# Generated by CloudAssist

environment = "dev"
location    = "UK South"

# Resource naming
resource_group_name = "rg-dev-cloudassist"

# Common tags
common_tags = {
  Environment = "dev"
  Project     = "CloudAssist"
  ManagedBy   = "Terraform"
  CreatedBy   = "GitOps"
  CostCenter  = "Infrastructure"
}






