# PROD Environment Variables
# Generated by CloudAssist

environment = "prod"
location    = "UK South"

# Resource naming
resource_group_name = "rg-prod-cloudassist"

# Common tags
common_tags = {
  Environment = "prod"
  Project     = "CloudAssist"
  ManagedBy   = "Terraform"
  CreatedBy   = "GitOps"
  CostCenter  = "Infrastructure"
}






