#!/bin/bash
# Terraform Validation Script
# Generated by CloudAssist

set -e

echo "🔍 Running Terraform validation checks..."

# Change to terraform directory
cd terraform

# Check Terraform formatting
echo "📋 Checking Terraform formatting..."
terraform fmt -check -recursive

# Initialize Terraform (without backend for validation)
echo "⚙️ Initializing Terraform..."
terraform init -backend=false

# Validate Terraform configuration
echo "✅ Validating Terraform configuration..."
terraform validate

# Run security checks if tools are available
if command -v tfsec &> /dev/null; then
    echo "🛡️ Running TFSec security scan..."
    tfsec .
fi

if command -v checkov &> /dev/null; then
    echo "🔍 Running Checkov compliance scan..."
    checkov -d .
fi

echo "✅ All validation checks passed!"
